### ISSUE TITLE
Error with oauth 

### ISSUE THREAD

**Issue by paragdas** [jasonjoh/node-calendar-sync#8]
Hi, I have followed the video and done exactly but I am getting error.

var oauth2 = require('simple-oauth2')(credentials);
                                     ^
TypeError: require(...) is not a function
    at Object.<anonymous> (C:\node-calendar-sync-cleanslate\node-calendar-sync-cleanslate\authHelper.js:40:38)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\node-calendar-sync-cleanslate\node-calendar-sync-cleanslate\app.js:12:18)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-calendar-sync@1.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-calendar-sync@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

So I modified var oauth2 = require('simple-oauth2')(credentials);
With
var oauth2 = require('simple-oauth2').create(credentials);

but now another error shows up

index.js:189
                throw error;
                ^

ValidationError: Invalid options provided to simple-oauth2 {
  "clientID": "181882ca-3b79-4e2e-9f31-46cef3fb26e2",
  "clientSecret": "*************************",
  "site": "https://login.microsoftonline.com/common",
  "authorizationPath": "/oauth2/v2.0/authorize",
  "tokenPath": "/oauth2/v2.0/token",
  "client" [1]: -- missing --
}

[1] "client" is required
    at Object.exports.process (C:\node-calendar-sync-cleanslate\node-calendar-sync-cleanslate\node_modules\joi\lib\errors.js:196:19)
    at internals.Object._validateWithOptions (C:\node-calendar-sync-cleanslate\node-calendar-sync-cleanslate\node_modules\joi\lib\types\any\index.js:675:31)
    at module.exports.internals.Any.root.validate (C:\node-calendar-sync-cleanslate\node-calendar-sync-cleanslate\node_modules\joi\lib\index.js:146:23)
    at module.exports.internals.Any.root.attempt (C:\node-calendar-sync-cleanslate\node-calendar-sync-cleanslate\node_modules\joi\lib\index.js:175:29)
    at Object.create (C:\node-calendar-sync-cleanslate\node-calendar-sync-cleanslate\node_modules\simple-oauth2\index.js:43:25)
    at Object.<anonymous> (C:\node-calendar-sync-cleanslate\node-calendar-sync-cleanslate\authHelper.js:39:39)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-calendar-sync@1.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-calendar-sync@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Parag\AppData\Roaming\npm-cache\_logs\2018-11-19T07_40_13_884Z-debug.log

Kindly help...

**Comment by jasonjoh** [comment]
The simple-oauth2 library had a breaking change a while back. The format of `credentials` is changed. See https://docs.microsoft.com/en-us/outlook/rest/node-tutorial#implementing-oauth2 for an example of how to setup the `credentials` object.
